<a href="https://colab.research.google.com/github/PalleGayathri/Gayathri-Reddy/blob/main/model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
scalar = np.array(5)
print("Scalar value:", scalar)

Scalar value: 5


In [2]:
vector = np.array([1, 2, 3])
print("Vector values:", vector)

Vector values: [1 2 3]


In [5]:
import numpy as np
scalar = np.array(5)
print("Scalar value:",scalar)
vector = np.array([1, 2, 3])
print("Vector values:", vector)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Tensor (Matrix):\n", matrix)
tensor_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Tensor:\n", tensor_3d)
tensor_4d = np.random.rand(2, 3, 4, 5)
print("Shape of 4D Tensor:", tensor_4d.shape)

Scalar value: 5
Vector values: [1 2 3]
2D Tensor (Matrix):
 [[1 2 3]
 [4 5 6]]
3D Tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of 4D Tensor: (2, 3, 4, 5)


In [7]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
def generate_data(num_samples):
  x1 = np.random.randint(0, 100, size=num_samples)
  x2 = np.random.randint(0, 100, size=num_samples)
  y = x1 + x2
  return np.vstack((x1, x2)).T, y
num_samples = 10000
X, y = generate_data(num_samples)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))
model.add(Dense(5, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(X_train, y_train, epochs=48, batch_size=32, validation_split=0.2)
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')
sample_input = np.array([[23, 45]])
predicted_sum = model.predict(sample_input)
print(f'Predicted Sum: {predicted_sum[0][0]}')

Epoch 1/48
200/200 [==============================] - 1s 3ms/step - loss: 4972.3608 - val_loss: 469.3689
Epoch 2/48
200/200 [==============================] - 0s 2ms/step - loss: 123.3578 - val_loss: 34.5835
Epoch 3/48
200/200 [==============================] - 0s 2ms/step - loss: 22.5128 - val_loss: 14.3999
Epoch 4/48
200/200 [==============================] - 0s 2ms/step - loss: 10.7380 - val_loss: 7.4479
Epoch 5/48
200/200 [==============================] - 0s 2ms/step - loss: 5.6264 - val_loss: 4.1098
Epoch 6/48
200/200 [==============================] - 0s 2ms/step - loss: 3.2902 - val_loss: 2.6444
Epoch 7/48
200/200 [==============================] - 0s 2ms/step - loss: 2.2224 - val_loss: 1.9338
Epoch 8/48
200/200 [==============================] - 0s 2ms/step - loss: 1.6432 - val_loss: 1.5165
Epoch 9/48
200/200 [==============================] - 0s 2ms/step - loss: 1.2964 - val_loss: 1.2385
Epoch 10/48
200/200 [==============================] - 0s 2ms/step - loss: 1.0371 - val_l